server {
    listen 8081 default_server;
    listen [::]:8081 default_server;
    server_name _;

    root /var/lib/arozos-pxe-se/http;
    autoindex on;
    sendfile on;
    tcp_nopush on;

    location / {
        try_files $uri $uri/ =404;
    }
}
